config/routes.rb
Rails.application.routes.draw do

  resources :topics do
    resources :posts, except: [:index]
    resources :sponsored_posts, except: [:index]
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]

    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
  end

  resources :users, only: [:new, :create, :show]

    resources :sessions, only: [:new, :create, :destroy]

  get 'about' => 'welcome#about'

  root 'welcome#index'

  end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
end

app/models/advertisements.rb
class Advertisements < ApplicationRecord
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :body, length: { minimum: 5 }, presence: true
  validates :user, presence: true

  after_create :send_favorite_emails

  private

  def send_favorite_emails
    post.favorites.each do |favorite|
      FavoriteMailer.new_comment(favorite.user, post, self).deliver_now
    end
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy

  after_create :create_vote

  default_scope { order('rank DESC')}

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true

  def up_votes
    votes.where(value: 1).count
  end

  def down_votes
    votes.where(value: -1).count
  end

  def points
    votes.sum(:value)
  end

  def update_rank
    age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
    new_rank = points + age_in_days
    update_attribute(:rank, new_rank)
  end

  def create_vote
    user.votes.create(value: 1, post: self)
  end
end

app/models/sponsored_post.rb
class SponsoredPost < ApplicationRecord
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :sponsored_posts

  validates :name, length: { minimum: 5 }, presence: true
  validates :description, length: { minimum: 15 }, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  before_save { self.email = email.downcase if email.present?}
  before_save { self.role ||= :member }

  validates :name, length: {minimum: 1, maximum: 100}, presence: true
  validates :password, presence: true, length: {minimum: 6}, if: "password_digest.nil?"
  validates :password, length: {minimum: 6}, allow_blank: true
  validates :email,
    presence: true,
    uniqueness:  {case_sensitive: false},
    length: { minimum: 3, maximum: 254 }

  has_secure_password

  enum role: [:member, :admin]

  def favorite_for(post)
    favorites.where(post_id: post.id).first
  end

  def avatar_url(size)
    gravatar_id = Digest::MD5::hexdigest(self.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end

  def blunt
    "My name is " + self.name.to_s
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :post
  after_save :update_post

  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote."}, presence: true

  private

  def update_post
    post.update_rank
  end
end

app/controllers/sponsored_posts_controller.rb
class SponsoredPostsController < ApplicationController
  def show
    @sponsored_post = SponsoredPost.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @sponsored_post = SponsoredPost.new
    @sponsored_post.topic = @topic
  end

  def edit
      @sponsored_post = SponsoredPost.find(params[:id])
  end

  def create
    @sponsored_post = SponsoredPost.new
    @sponsored_post.title = params[:sponsored_post][:title]
    @sponsored_post.body = params[:sponsored_post][:body]
    @sponsored_post.price = params[:sponsored_post][:price]
    @topic = Topic.find(params[:topic_id])

    @sponsored_post.topic = @topic

    if @sponsored_post.save
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @sponsored_post]
    else
      flash.now[:alert] = "There was an error saving the post. Please try again."
      render :new
    end
  end

  def update
    @sponsored_post = SponsoredPost.find(params[:id])
    @sponsored_post.title = params[:sponsored_post][:title]
    @sponsored_post.body = params[:sponsored_post][:body]
    @topic = Topic.find(params[:topic_id])

    @sponsored_post.topic = @topic

    if @sponsored_post.save
      flash[:notice] = "Post was updated"
      redirect_to [@sponsored_post.topic, @sponsored_post]
    else
      flash.now["alert"] = "There was an error saving the post. Please try again."
      render :edit
    end
  end

  def destroy
    @sponsored_post = SponsoredPost.find(params[:id])


    if @sponsored_post.destroy
      flash[:notice] = "\"#{@sponsored_post.title}\" was deleted successfully."
      redirect_to @sponsored_post.topic
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :show
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def user_is_authorized_for_comment(comment)
    current_user && (current_user == comment.user || current_user.admin?)
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def user_is_authorized_for_post?(post)
    current_user && (current_user == post.user || current_user.admin?)
  end

  def user_is_authorized_to_edit?(post)
    current_user && (current_user == post.user || current_user.admin? || current_user.moderator?)
  end
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    
    def create_session(user)
        session[:user_id] = user.id 
    end
    
    def destroy_session(user)
         session[:user_id] = nil
    end
    
    def current_user
        User.find_by(id: session[:user_id])
    end
    
end

app/helpers/sponsored_posts_helper.rb
module SponsoredPostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
  def user_is_authorized_for_topics?
    current_user && current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/sponsored_posts/edit.html.erb
<div class="row">
  <div class="col-md-4">
    <p>Guidelines for sponsored_posts</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A"</li>
      <li>The incessent use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for [@sponsored_post.topic, @sponsored_post] do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter sponsored_post body" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/sponsored_posts/new.html.erb
<h1>New Sponsored Post</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for sponsored_posts</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for [@topic, @sponsored_post] do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: 'Enter sponsored post title' %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: 'Enter sponsored post body' %>
      </div>
      <div class="form-group">
        <%= f.label :price %>
        <%= f.number_field :price, class: 'form-control', placeholder: 'Enter sponsored post price' %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/sponsored_posts/show.html.erb
<h1><%= @sponsored_post.title %></h1>


<div class="row">
  <div class="col-md-8">
    <p><%= @sponsored_post.body %></p>
  </div>
  <div class="col-md-4">

    <%= link_to "Edit", edit_topic_sponsored_post_path(@sponsored_post.topic, @sponsored_post), class: 'btn btn-success' %>
    <%= link_to "Delete Post", [@sponsored_post.topic, @sponsored_post], method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure?'} %>
  </div>
</div>